// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiPLIzE_ORiD9CwQDsu9VYajxs6F0Wlu4',
    appId: '1:424543315235:android:faf73a795f4d4e8d895896',
    messagingSenderId: '424543315235',
    projectId: 'alkhatouna-boutique-8d85a',
    storageBucket: 'alkhatouna-boutique-8d85a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCw9keYSXeojFpuzDsbydiqcOkXzNxwN7g',
    appId: '1:424543315235:ios:d88c60e908b0d692895896',
    messagingSenderId: '424543315235',
    projectId: 'alkhatouna-boutique-8d85a',
    storageBucket: 'alkhatouna-boutique-8d85a.firebasestorage.app',
    androidClientId: '424543315235-8jcjr8v2la06i9ebi61lvdr8jbpvjsd0.apps.googleusercontent.com',
    iosClientId: '424543315235-kknfb3759d9bitm4112a9604fr6tdsku.apps.googleusercontent.com',
    iosBundleId: 'com.khatouna.Boutique',
  );
}
